Models/ErrorViewModel.cs
namespace InventoryEase.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/InventoryViewModel.cs
namespace InventoryEase.Models
{
    public class InventoryViewModel
    {
        public IEnumerable<NavSectionModel> NavSections { get; set; }
        public IEnumerable<ProductsModel> Products { get; set; }
        public List<NavSectionModel> AllNavSections { get; set; }
    }
}

Models/NavSectionModel.cs
using System.ComponentModel.DataAnnotations;


namespace InventoryEase.Models
{
    public class NavSectionModel
    {
        public int Id { get; set; }

        [Required]
        public string? Name { get; set; }

        public List<ProductsModel>? Products { get; set; }

    }
}

Models/ProductsModel.cs
using System.ComponentModel.DataAnnotations;

namespace InventoryEase.Models
{
    public class ProductsModel
    {
        public int Id { get; set; }
        [Required]public string? Name { get; set; }
        [Required]public string? Size { get; set; }
        [Required]public string? Image { get; set; }
        [Required] public int OrderTreshold { get; set; }
        [Required]public int OrderQuantity { get; set; }
        [Required]public DateTime CreatedDateTime { get; set; } = DateTime.Now;

        public int NavSectionId { get; set; }
        public NavSectionModel? NavSection { get; set; }
    }
}

Controllers/HomeController.cs
using InventoryEase.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace InventoryEase.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/InventoryController.cs
using InventoryEase.Data;
using InventoryEase.Models;
using Microsoft.AspNetCore.Mvc;

namespace InventoryEase.Controllers
{
    public class InventoryController : Controller
    {
        private readonly ApplicationDbContext _context;
        public InventoryController(ApplicationDbContext db)
        {
            _context = db;
        }
        public IActionResult Index()
        {
            IEnumerable<NavSectionModel> sections = _context.NavSections;
            IEnumerable<ProductsModel> products = _context.Products;
            var inventoryViewModel = new InventoryViewModel()
            {
                    NavSections = sections,
                    Products = products
                };

            return View(inventoryViewModel);
        }
        //Get
        [HttpGet]
        public IActionResult SectionInventory(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var allNavSections = _context.NavSections.ToList();
            var navSectionFromDb = _context.NavSections.Find(id);
            if (navSectionFromDb == null)
            {
                return NotFound();
            }

            // Retrieve associated products for the NavSection
            var productsForSection = _context.Products.Where(p => p.NavSectionId == id).ToList();

            var inventoryViewModel = new InventoryViewModel
            {
                AllNavSections= allNavSections ,
                NavSections = new List<NavSectionModel> { navSectionFromDb },
                Products = productsForSection
            };

            return View(inventoryViewModel);
        }
    }
}

Controllers/ProductsController.cs
using InventoryEase.Data;
using InventoryEase.Models;
using Microsoft.AspNetCore.Mvc;

namespace InventoryEase.Controllers
{
    public class ProductsController : Controller
    {
        public readonly ApplicationDbContext _context;

        public ProductsController(ApplicationDbContext db)
        {
            _context = db;
        }
        public IActionResult Index()
        {

            return View();
        }

        [HttpPost]
        public IActionResult CreateProduct(int? id ,ProductsModel product)
        {
            if (product != null)
            {
                var NewProduct = new ProductsModel
                {
                    Name = product.Name,
                    Size = product.Size,
                    Image = product.Image,
                    OrderTreshold = product.OrderTreshold,
                    OrderQuantity = product.OrderQuantity,
                    NavSectionId = product.NavSectionId,
                };
             
                _context.Products.Add(NewProduct);
                _context.SaveChanges();
                return RedirectToAction("SectionInventory","Inventory", new { id = product.NavSectionId });
            }
            else
            {
                return NotFound();
            }  
        }
        
    }
}

Controllers/SectionController.cs
using InventoryEase.Data;
using InventoryEase.Models;
using Microsoft.AspNetCore.Mvc;

namespace InventoryEase.Controllers
{
    public class SectionController : Controller
    {
        public readonly ApplicationDbContext _context;
        public SectionController(ApplicationDbContext db)
        {
            _context = db;
            
        }
        public IActionResult Index()
        {
            return View();
        }

        //GET
        public IActionResult Create()
        {
            return View();
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(NavSectionModel obj)
        {
            
            if (ModelState.IsValid) {
                _context.NavSections.Add(obj);
                _context.SaveChanges();
                TempData["success"] = "Section Created successfully";
                return RedirectToAction("Index", "Inventory");
            }
          
            return View(obj);
        }

        //GET
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var navSectionFromDb = _context.NavSections.Find(id);
            if (navSectionFromDb == null)
            {
                return NotFound();
            }
            return View(navSectionFromDb);
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(NavSectionModel obj)
        {

            if (ModelState.IsValid)
            {
                _context.NavSections.Update(obj);
                _context.SaveChanges();
                TempData["success"] = "Section updated successfully";
                return RedirectToAction("Index", "Inventory");
            }

            return View(obj);
        }
        //GET
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var navSectionFromDb = _context.NavSections.Find(id);
            if (navSectionFromDb == null)
            {
                return NotFound();
            }
            return View(navSectionFromDb);
        }
        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePOST(int? id)
        {
            var obj = _context.NavSections.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
          
            _context.NavSections.Remove(obj);
            _context.SaveChanges();
            TempData["success"] = "Section deleted successfully";
            return RedirectToAction("Index", "Inventory");
                     
        }
       
      

    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<div class="container pt-5 mt-5">
    <div class="row align-items-center">
        <div class="col-md-6">
            <h1 class="display-4">Welcome to Our Website</h1>
            <p>Discover the best in <a href="/products">products</a> and <a href="/services">services</a>.</p>
            <a class="btn btn-primary" href="/shop">Shop Now</a>
        </div>
        <div class="col-md-6">
            <img class="homeImage w-100" src="https://assets-global.website-files.com/59b85cfc56db830001760b29/6228fc0d3c5130cac8f19c09_Why%20Restaurant%20Inventory%20Management%20Matters.jpg" alt="Welcome Image" />
        </div>
    </div>
</div>

<div class="container mt-xxl-5">
    <div class="row align-items-center">
        <!-- Right side with a different message and image -->
        <div class="col-md-6">
            <img class="homeImage w-75" src="https://images.squarespace-cdn.com/content/v1/56a2785c69a91af45e06a188/1573145250046-0O78VJPX91Y3WETZXLV8/Restaurant-Inventory-Management.png?format=1500w" alt="Another Image" />
            <h2>Upgrade Your Experience</h2>
            <p>Explore our premium application and take your business to the next level.</p>
            <a class="btn btn-success" href="/buy">Get Started</a>
        </div>
    </div>
</div>

Views/Inventory/Index.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
@model InventoryViewModel

<div class="container-fluid">
    <div class="row">
        <!-- Navigation Bar (15% width) -->
        <div class="col-md-2 sidebar-wrapper" style="max-width:100%; border-right: solid 2px black;">
            <div>
                <a class="nav-link" asp-area="" asp-controller="Inventory" asp-action="Index"><h2 class="mt-3"><i class="bi bi-egg-fried"></i> Flacos Tacos</h2></a>                
            </div>
           @* -------------------- left Navbar butoon-------------------- *@
            <nav>
                <div class="nav nav-tabs pb-4" id="nav-tab" role="tablist">
                    <button class="nav-link active side-navbar-bottons" id="section-tab" data-bs-toggle="tab" data-bs-target="#nav-section" type="button" role="tab" aria-controls="nav-section" aria-selected="true">Sections</button>
                    <button class="nav-link side-navbar-bottons" id="nav-providers-tab" data-bs-toggle="tab" data-bs-target="#nav-providers" type="button" role="tab" aria-controls="nav-providers" aria-selected="false">Providers</button>
                </div>
            </nav>
            <div class="tab-content text-center" id="nav-tabContent">             
                <div class="tab-pane fade show active pt-4" id="nav-section" role="tabpanel" aria-labelledby="section-tab" tabindex="0">
                    <a asp-controller="Section" asp-action="Create">Add section  <i class="bi bi-plus-square"></i></a>
                    @* <-------- Navegation Sections------------> *@
                    @if (Model != null)
                    {
                        <div class=" pt-2">
                            <ul class="list-group">
                                @foreach (var obj in Model.NavSections)
                                {
                                    <li class="list-group-item d-flex justify-content-between align-items-center">
                                        <a class="nav-link" asp-controller="Inventory" asp-action="SectionInventory" asp-route-id="@obj.Id"><h5>@obj.Name</h5></a>
                                        <div>
                                           @*  <a asp-controller="Section" asp-action="Edit" asp-route-id="@obj.Id"><span class="badge bg-primary rounded-pill" style="font-size: 10px;"><i class="bi bi-pencil-square small"></i></span></a>
                                            <a asp-controller="Section" asp-action="Delete" asp-route-id="@obj.Id"><span class="badge bg-primary rounded-pill" style="font-size: 10px;"><i class="bi bi-trash"></i></span></a> *@
                                            <button data-toggle="modal" data-target="#myModal1" class="badge bg-primary rounded-pill" style="font-size: 10px;"><i class="bi bi-pencil-square small"></i></button>
                                            <button data-bs-toggle="modal" data-bs-target="#deleteModal" class="badge bg-primary rounded-pill" style="font-size: 10px;"><i class="bi bi-trash"></i></button>
 
                                            <!-- Modal -->
                                            <div class="modal fade" id="deleteModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
                                                <div class="modal-dialog">
                                                    <div class="modal-content">
                                                        <div class="modal-header">
                                                            <h1 class="modal-title fs-5" id="deleteModalLabel">Are you sure you want to delete</h1>
                                                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                                        </div>
                                                        <div class="modal-body bg-danger">
                                                            <a asp-controller="Section" asp-action="Delete" asp-route-id="@obj.Id"><span >@obj.Name</span></a>
                                                        </div>
                                                        <div class="modal-footer">
                                                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                                                            <button type="button" class="btn btn-primary">Cancel</button>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>



                                        </div>
                                    </li>

                                }
                            </ul>
                        </div>

                    }

                </div>
                <div class="tab-pane fade pt-4" id="nav-providers" role="tabpanel" aria-labelledby="nav-providers-tab" tabindex="0">
                    <a asp-controller="Section" asp-action="Create">Add provider  <i class="bi bi-plus-square"></i></a>
                </div>
            </div>
     
        </div>
        <!-- Table Area (80% width) -->
        <div class="col-md-10">
                <div class="row pb-1">
                    <div class="col-3 mt-5">
                        <h1 class="header-title" style="font-weight: bold; font-size: 36px;">Iventory Tracking</h1>                   
                    </div>
                @* <-------- Add Product Model section------------>
                <div class="text-end">
                    <button type="button" class="btn btn-primary " data-bs-toggle="modal" data-bs-target="#ProductModal">Add Product </button>
                    <div class="modal fade modal-xl text-center" id="ProductModal" tabindex="-1" aria-labelledby="ProductModalLabel" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">

                                <div class="modal-header text-center">
                                    <h1 class="modal-title fs-2" id="ProductModalLabel">Add new product:</h1>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                </div>
                                <div class="modal-body">
                                    <form method="post" asp-controller="Products" asp-action="CreateProduct">
                                        <div class="form-group">
                                            <label class="custom-label-section" for="sectionId">Select Section:</label>
                                            <select class="form-control custom-input text-center" id="sectionId" name="NavSectionId">
                                                @foreach (var obj in Model.NavSections)
                                                {
                                                    <option value="@obj.Id">@obj.Name</option>
                                                }
                                            </select>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <div class="form-group">
                                                    <label class="custom-label" for="Name">Name:</label>
                                                    <input type="text" class="form-control custom-input" name="Name">
                                                </div>
                                                <div class="form-group">
                                                    <label class="custom-label" for="Size">Size:</label>
                                                    <input type="text" class="form-control custom-input" name="Size">
                                                </div>
                                                <div class="form-group">
                                                    <label class="custom-label" for="Image">Image:</label>
                                                    <input type="text" class="form-control custom-input" name="Image">
                                                </div>
                                            </div>
                                            <div class="col-md-6 mb-2">
                                                <div class="form-group">
                                                    <label class="custom-label" for="OrderTreshold">Order Threshold:</label>
                                                    <input type="text" class="form-control custom-input" name="OrderTreshold">
                                                </div>
                                                <div class="form-group">
                                                    <label class="custom-label" for="OrderQuantity">Order Quantity:</label>
                                                    <input type="text" class="form-control custom-input" name="OrderQuantity">
                                                </div>
                                                <div class="form-group">
                                                    <label class="custom-label" for="CreatedDateTime">Date:</label>
                                                    <input type="text" class="form-control custom-input" name="CreatedDateTime">
                                                </div>
                                            </div>

                                        </div>
                                        <button type="submit" class="btn btn-primary custom-button ">Create product</button>

                                    </form>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
              @*   @if (User.Identity.IsAuthenticated)
                {
                    <div class="col-9 text-end" style="font-size: 23px;">
                        <div>
                            <h4 class="nav-link text-dark mt-5" style="margin-right:150px" asp-area="Identity" asp-page="/Account/Manage/Index" title="Manage">
                               
                                Hello @User.Identity?.Name!
                            </h4>
                        </div>                                                    
                    </div>  
                } *@
            </div>          
    <table class="table table-hover text-center">
                <thead>
                    <tr class="table-dark">
                        <th scope="row">Name</th>
                        <th >Sizes</th>
                        <th >Images</th>
                        <th >Order Treshold</th>
                        <th >Order Quantity</th>
                        <th >date</th>                      
                    </tr>
                </thead>
                <tbody>
                    <!-- Rows will be dynamically added here using JavaScript -->
                    @if(Model != null){
                        foreach(var obj in Model.Products){
                            <tr class="table-light">                   
                                <td>@obj.Name</td>
                                <td>@obj.Size</td>
                                <td>
                                    <img src="@obj.Image" alt="Product Image" width="50" height="30" />
                                </td>
                                <td>@obj.OrderTreshold</td>
                                <td>@obj.OrderQuantity</td>
                                <td>@obj.CreatedDateTime</td>
                            </tr>
                        }
                    }
                </tbody>
            </table>
        </div>
    </div>
  </div>

Views/Inventory/SectionInventory.cshtml
@model InventoryViewModel

<div class="container-fluid">
    <div class="row">
        <!-- Navigation Bar (15% width) -->
        <div class="col-md-2 sidebar-wrapper" style="max-width:100%;border-right: solid 2px black;">
            <div>
                <a class="nav-link" asp-area="" asp-controller="Inventory" asp-action="Index"><h2 class="mt-3"><i class="bi bi-egg-fried"></i> Flacos Tacos</h2></a>
            </div>
            @* -------------------- left Navbar butoon-------------------- *@
            <nav>
                <div class="nav nav-tabs pb-4" id="nav-tab" role="tablist">
                    <button class="nav-link active side-navbar-bottons" id="section-tab" data-bs-toggle="tab" data-bs-target="#nav-section" type="button" role="tab" aria-controls="nav-section" aria-selected="true">Sections</button>
                    <button class="nav-link side-navbar-bottons" id="nav-providers-tab" data-bs-toggle="tab" data-bs-target="#nav-providers" type="button" role="tab" aria-controls="nav-providers" aria-selected="false">Providers</button>
                </div>
            </nav>
            <div class="tab-content text-center" id="nav-tabContent">
           
            <div class="tab-pane fade show active pt-4" id="nav-section" role="tabpanel" aria-labelledby="section-tab" tabindex="0">
                 <a asp-controller="Section" asp-action="Create">Add section  <i class="bi bi-plus-square"></i></a>
                    @if (Model != null)
                    {
                        <div class=" pt-2">
                            <ul class="list-group">                    
                                @if (Model != null && Model.AllNavSections != null){
                                    @foreach (var obj in Model.AllNavSections)
                                    {
                                        <li class="list-group-item d-flex justify-content-between align-items-center">
                                        <a style="text-decoration:none" asp-controller="Inventory" asp-action="SectionInventory" asp-route-id="@obj.Id"><h5>@obj.Name</h5></a>
                                        <div>
                                            <a asp-controller="Section" asp-action="Edit" asp-route-id="@obj.Id"><span class="badge bg-primary rounded-pill" style="font-size: 10px;"><i class="bi bi-pencil-square small"></i></span></a>
                                            <a asp-controller="Section" asp-action="Delete" asp-route-id="@obj.Id"><span class="badge bg-primary rounded-pill" style="font-size: 10px;"><i class="bi bi-trash"></i></span></a>
                                        </div>
                                        </li>
                                    }
                                }                     
                            </ul>
                        </div>
                    }
                </div>
                <div class="tab-pane fade pt-4" id="nav-providers" role="tabpanel" aria-labelledby="nav-providers-tab" tabindex="0">
                    <a asp-controller="Section" asp-action="Create">Add provider  <i class="bi bi-plus-square"></i></a>
                </div>
            </div>
        </div>
        <!-- Table Area (80% width) -->
        <div class="col-md-10">
            <div class="row pb-1">
                <div class="col-3 mt-5">
                    <h1 class="header-title" style="font-weight: bold; font-size: 36px;">Iventory Tracking</h1>
                </div>
                @* <-------- Model section------------> *@
                <div class="text-end">
                    <button type="button" class="btn btn-primary " data-bs-toggle="modal" data-bs-target="#ProductModal">Add Product </button>
                    <div class="modal fade modal-xl text-center" id="ProductModal" tabindex="-1" aria-labelledby="ProductModalLabel" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h1 class="modal-title fs-2" id="ProductModalLabel">Add new product:</h1>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                </div>
                                <div class="modal-body">

                                    <form method="post" asp-controller="Products" asp-action="CreateProduct">
                                        <div class="form-group">
                                            <label class="custom-label-section" for="sectionId">Select Section:</label>
                                            <select class="form-control custom-input text-center" id="sectionId" name="NavSectionId">
                                                @foreach (var obj in Model.NavSections)
                                                {
                                                    <option value="@obj.Id">@obj.Name</option>
                                                }
                                            </select>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <div class="form-group">
                                                    <label class="custom-label" for="Name">Name:</label>
                                                    <input type="text" class="form-control custom-input" name="Name">
                                                </div>
                                                <div class="form-group">
                                                    <label class="custom-label" for="Size">Size:</label>
                                                    <input type="text" class="form-control custom-input" name="Size">
                                                </div>
                                                <div class="form-group">
                                                    <label class="custom-label" for="Image">Image:</label>
                                                    <input type="text" class="form-control custom-input" name="Image">
                                                </div>
                                            </div>
                                            <div class="col-md-6 mb-2">
                                                <div class="form-group">
                                                    <label class="custom-label" for="OrderTreshold">Order Threshold:</label>
                                                    <input type="text" class="form-control custom-input" name="OrderTreshold">
                                                </div>
                                                <div class="form-group">
                                                    <label class="custom-label" for="OrderQuantity">Order Quantity:</label>
                                                    <input type="text" class="form-control custom-input" name="OrderQuantity">
                                                </div>
                                                <div class="form-group">
                                                    <label class="custom-label" for="CreatedDateTime">Date:</label>
                                                    <input type="text" class="form-control custom-input" name="CreatedDateTime">
                                                </div>
                                            </div>

                                        </div>
                                        <button type="submit" class="btn btn-primary custom-button ">Create product</button>
                                    </form>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
            <table class="table table-hover text-center">
                <thead>
                    <tr class="table-dark">
                        <th scope="row">Name</th>
                        <th>Sizes</th>
                        <th>Images</th>
                        <th>Order Treshold</th>
                        <th>Order Quantity</th>
                        <th>date</th>
                    </tr>
                </thead>
                <tbody>
                    <!-- Rows will be dynamically added here using JavaScript -->
                    @if (Model != null)
                    {
                        foreach (var obj in Model.Products)
                        {
                            <tr class="table-light">
                                <td>@obj.Name</td>
                                <td>@obj.Size</td>
                                <td>
                                    <img src="@obj.Image" alt="Product Image" width="50" height="30" />
                                </td>
                                <td>@obj.OrderTreshold</td>
                                <td>@obj.OrderQuantity</td>
                                <td>@obj.CreatedDateTime</td>
                            </tr>
                        }
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>